version: '3.3'

services:
  app:
    build: ./
    image: playground
    volumes:
      - "./:/app/"
    ports:
      - "5000:5000"
    command: sh -c ./start.sh
    networks:
      - isolated
networks:
  isolated:
